language: python
python:
  - 3.6
  - 3.8

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

# command to run tests
script:
  - pre-commit run --all-files
  - pyflakes mozilla_bitbar_devicepool/*.py
  - pytest -v mozilla_bitbar_devicepool
